version: '3.8'
services:
  app:
    build: .
    container_name: conexa_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=conexa
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
    command: ["sh", "-c", "npm install && npx sequelize-cli db:migrate && npm start"]

  db:
    image: mysql:8.0
    container_name: conexa_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: conexa
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6.0
    container_name: conexa_redis
    restart: always
    hostname: redis
    networks:
      - default
    ports:
      - "6379:6379"

volumes:
  db_data: